# site settings

title: Shoury Gupta | An Enthusiast
description: Portfolio Site and Blog for SG
taglong: Portfolio Site and Blog for SG
tagshort: SG's site
url: https://theguptaempire.github.io/cvless/
baseurl: ""
permalink: pretty
repo: https://github.com/TheGuptaEmpire/cvless

# author settings

author:
  name: Shoury Gupta
  email: shoury24gupta@.com
photo: /assets/jpg/photo.png

# social media links

social:
  github: TheGuptaEmpire
  instagram: suryagupt_sg

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
